#!/bin/bash

function	init_libash()
{
	# install lib_bash
	DIR_LIB_BASH="${HOME}/.local/lib/lib_bash"
	[ ! -d "${DIR_LIB_BASH}" ] && \
		bash -c "$(curl -sL https://bit.ly/lib_bash)"

	# source .config
	source "${DIR_LIB_BASH}/.config"

	## test if work, in this case update lib_bash
	# cli_update
}

function	init_dotfiles()
{
	# source .config
	PATH_CONFIG=$(realpath ${BASH_SOURCE[0]})
	DIR_BASE=${PATH_CONFIG%/*}
	source "${DIR_BASE}/.config"

	LOG_PAD_STR="${LOG_PAD_STR_BAK}"
}

function	init_tui()
{
	source ${DIR_BASE}/src/tui
}

function	init_main()
{
	init_libash
	init_dotfiles
	init_tui
}

init_main

## OTHERS
# MAIN

function	test_menu()
{
	MENU_TEST_SEL_ID=1
	MENU_TEST_TITLE="TEST MENU"
	MENU_TEST_PROMPT="   ITEM AVAILABLE\n\n"
	MENU_TEST_ITEM_ORDER=(
		"menu_input"
		"TEST_VAR_STRING"
		"bash"
		"git"
		"not_loaded_module"
		"TEST_VAR_BOOL"
		"TEST_VAR_PATH_DIR"
		"TEST_VAR_PATH_EXEC"
		"TEST_VAR_PATH_FILE"
		"TEST_VAR_PATH_NOT_FOUND"
		"TEST_VAR_PATH_LIEN"
		"TEST_VAR_INT"
	)
	MENU_TEST_ITEM_NAME=(
		"menu input"
		"test var string"
		"BASH"
		"git"
		"not loaded module"
		"test var bool"
		"test var path dir"
		"test var path exec"
		"test var path file"
		"test var path not_found"
		"test var path lien"
		"test var int"
	)

	declare -A MENU_TEST_ITEM=(
		["menu_input"]="function"
		["bash"]="module"
		["git"]="module"
		["module_not_found"]="module"
		["TEST_VAR_STRING"]="var:string"
		["TEST_VAR_BOOL"]="var:bool"
		["TEST_VAR_PATH_DIR"]="var:path"
		["TEST_VAR_PATH_EXEC"]="var:path"
		["TEST_VAR_PATH_FILE"]="var:path"
		["TEST_VAR_PATH_NOT_FOUND"]="var:path"
		["TEST_VAR_PATH_LIEN"]="var:path"
		["TEST_VAR_INT"]="var:int"
	)

	TEST_VAR_BOOL=false
	TEST_VAR_PATH=""
	TEST_VAR_PATH_DIR="${HOME}"
	TEST_VAR_PATH_EXEC="${HOME}/.fehbg"
	TEST_VAR_PATH_FILE="${HOME}/.bashrc"
	TEST_VAR_PATH_NOT_FOUND="/NOT/FOUND"
	TEST_VAR_PATH_LIEN="/dev/disk/by-label/Data"
	TEST_VAR_INT=1234
	TEST_VAR_STRING="ABCD"
	menu_run_loop "TEST"
}

MENU_ID="MAIN"
MENU_MAIN_SEL_ID=1
MENU_MAIN_TITLE="Made by Pixailz"
MENU_MAIN_PROMPT="   Available modules:\n\n"

MENU_MAIN_ITEM_ORDER=("test_menu")
MENU_MAIN_ITEM_NAME=("Test menu")
declare -A MENU_MAIN_ITEM=(
	["test_menu"]="function"
)

for mods in ${MODULE[@]}; do
	MENU_MAIN_ITEM[${mods}]="module"
	MENU_MAIN_ITEM_ORDER+=("${mods}")
	MENU_MAIN_ITEM_NAME+=("${mods^^}")
done

RUNNING_MAIN="1"

# keypress
while [ "${RUNNING_MAIN}" == "1" ]; do
	menu_fill_title "KEY ${KEY_PRESS} PRESSED"
	menu_render
	key_press_main
	key_post_press_main
done
