#!/bin/bash

## BINDED FUNCTION

function	pre::install::bash()
{
	# make linux use local time in case of dual boot
	timedatectl set-local-rtc 1 --adjust-system-clock
	utils::mkdir "${TARGET_DIR}"
}

function	install::bash()
{
	utils::move_dir "${MOD_FILE_DIR}" "${TARGET_DIR}" y
}

function	post::install::bash()
{
	log::warn "to make effect you have to source your ${RED}~/.bashrc${RST}" 1
}

function	menu::bash()
{
	menu::set::title
	menu::render
}

# Start
function	module::start()
{
	local	base="${BASH_SOURCE[0]?}"

	# remove filename
	base="${base/install/}"
	# if base dir is relative, suffix PWD to base
	if [[ ${base} =~ ^\./.*$ ]]; then
		base="${PWD}/${base}"
	fi
	# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
	if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
		source "${base}../../dot"

		## BINDED FUNCTION
		module::install "${MOD_NAME}"
	fi
}

module::start
