#!/bin/bash

if [ -z "${IMPORTED_TUI:-}" ]; then
declare -gr IMPORTED_TUI=1

# VARIABLES
MAIN_TITLE="TITLE v1.0.0"

FONT="${WHI}"

SELECTED_FMT_BEG="${UND}"
UND_RST="\x1b[24m"
REV_RST="\x1b[27m"
SELECTED_FMT_END="${UND_RST}"

CURRENT_MODULE=""

BO_SHEB="$"
# ╒═╕
# │ │
# ╘═╛
BO_UR="╕"		# UPPER RIGHT
BO_UL="╒"		# UPPER LEFT
BO_HO="═"		# HORIZONTAL
BO_VE="│"		# VERTICAL
BO_LR="╛"		# LOWER RIGHT
BO_LL="╘"		# LOWER LEFT
BO_DS="╫"		# DEAD SINGLE
BO_DD="╪"		# DEAD DOUBLE

# # ╔═╗
# # ║ ║
# # ╚═╝
# BO_UR="╗"
# BO_UL="╔"
# BO_HO="═"
# BO_VE="║"
# BO_LR="╝"
# BO_LL="╚"

## NAMED ARRAY
# KEYCODE DECLARATION
declare -gA KS=(
	["A"]=$'\x61'
	["D"]=$'\x64'
	["S"]=$'\x73'
	["W"]=$'\x77'
	["ARROW_UP"]=$'\x1b\x5b\x41'
	["ARROW_DOWN"]=$'\x1b\x5b\x42'
	["ARROW_RIGHT"]=$'\x1b\x5b\x43'
	["ARROW_LEFT"]=$'\x1b\x5b\x44'
	["ENTER"]=$'\x0a'
	["ESC"]=$'\x1b'
	["SPACE"]=$'\x20'
	["TILDE"]=$'\x7e'
	["RETURN"]=$'\x7f'
	["F1"]=$'\x1b\x4f\x50'
	["F2"]=$'\x1b\x4f\x51'
	["F3"]=$'\x1b\x4f\x52'
	["F4"]=$'\x1b\x4f\x53'
	["F5"]=$'\x1b\x5b\x31\x35\x7e'
	["F6"]=$'\x1b\x5b\x31\x37\x7e'
	["F7"]=$'\x1b\x5b\x31\x38\x7e'
	["F8"]=$'\x1b\x5b\x31\x39\x7e'
	["F9"]=$'\x1b\x5b\x32\x30\x7e'
	["F10"]=$'\x1b\x5b\x32\x31\x7e'
	["F11"]=$'\x1b\x5b\x32\x32\x7e'
	["F12"]=$'\x1b\x5b\x32\x34\x7e'
)

SIZE_BOX=60

source ${DIR_BASE}/src/utils
source ${DIR_BASE}/src/menu
source ${DIR_BASE}/src/input
source ${DIR_BASE}/src/escape
source ${DIR_BASE}/src/selection

fi
